### ISSUE TITLE
Dependency on non-existent module EcomDev_PHPUnit on production servers

### ISSUE THREAD

**Issue by azambon** [bitbull-team/magento-module-satispay#10]
https://github.com/bitbull-team/magento-module-satispay/blob/0c597a2792c4b9c0ffb89ee5d3a84c5e23410f68/src/app/etc/modules/Bitbull_SatispayTest.xml#L9

Hi @renatocason, it's still me (I know that by now you are hating me...)

Just found another little problem: the line I referenced seems to cause some problems on production servers (usually PHP notices when running 98magerun commands).
This is because Magento seems to have a slight bug where it still (partially) checks for dependencies of disabled modules.
Take a look at Mage_Core_Model_Config line 843 (https://github.com/amacgregor/magento-1.7.0.2/blob/3991bf31fdc7d6040279c78e932b148df7d7c7da/app/code/core/Mage/Core/Model/Config.php#L843): that loop iterates on every defined module in Magento, including disabled ones (like Bitbull_SatispayTest). In a production server the module EcomDev_PHPUnit will not be present, and so the line 851 will generate a notice because the key "EcomDev_PHPUnit" cannot be found in the $modules array.

Notice that line 846 does not complain because the first check immediately returns false and so the additional checks are not executed.

This can also happen if someone does not have EcomDev_PHPUnit installed at all, not even on development machines.

A quick fix would be to remove this explicit dependency to EcomDev_PHPUnit.

**Comment by renatocason** [comment]
Hi @azambon,

Sorry for the late reply. I checked and tests work even without that, so I removed.
I merged the other PRs as well.

Thanks again for the contributions!

Best,
Renato

**Comment by azambon** [comment]
Hi @renatocason ,

thank you very much, both for this issue and for the other PRs.
