### ISSUE TITLE
Method Bitbull_Satispay_Model_Logger::debug() causes a warning

### ISSUE THREAD

**Issue by azambon** [bitbull-team/magento-module-satispay#5]
The method Bitbull_Satispay_Model_Logger::debug() causes a warning (depending on the PHP error level) because the method signature is not compatible with Varien_Object::debug().

Does this class really need to extend anything? Perhaps it's enough to remove the "extends Mage_Core_Model_Abstract" part to solve this.

**Comment by renatocason** [comment]
Hi @azambon ,

Thanks for your feedback, I just pushed a fix to master if you want to check that it works for you.
I will proceed with a new release once the other issue is fixed, too.

Regards,
Renato
