### ISSUE TITLE
Mage::getModel('core/logger') fails on Magento 1.7

### ISSUE THREAD

**Issue by azambon** [bitbull-team/magento-module-satispay#6]
As the title says, if the Mage_Core_Model_Logger class in not present in a specific Magento version (such as CE 1.7), then the line Mage::getModel('core/logger') inside Bitbull_Satispay_Model_Logger throws an error.
Since the module's class is already capable of working without a logger object, perhaps a try/catch may be enough to solve this problem?

**Comment by renatocason** [comment]
Hi @azambon ,

Thanks for your feedback. From my tests on 1.7.0.2 I get null on that _getModel_ call, so the function works correctly falling back to _Mage::log_.
What exception do you get, and do you have any particular configuration?

Thanks,
Renato

**Comment by azambon** [comment]
Hi,

The exact error is:

Warning: include(Mage/Core/Model/Logger.php): failed to open stream: No such file or directory  in /var/www/makehandbuy-store/app/code/local/Varien/Autoload.php on line 98

As you can see it's a warning, so it also depends on the PHP settings. If PHP is set to ignore warnings, then the code execution can happily continue past the error. However, if warnings are not ignored, then an exception is thrown.

Here's the complete stack trace in case you need it:

#0 /var/www/makehandbuy-store/app/code/local/Varien/Autoload.php(98): mageCoreErrorHandler(2, 'include(Mage/Co...', '/var/www/makeha...', 98, Array)
#1 /var/www/makehandbuy-store/app/code/local/Varien/Autoload.php(98): include()
#2 [internal function]: Varien_Autoload->autoload('Mage_Core_Model...')
#3 [internal function]: spl_autoload_call('Mage_Core_Model...')
#4 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/Config.php(1355): class_exists('Mage_Core_Model...')
#5 /var/www/makehandbuy-store/app/Mage.php(473): Mage_Core_Model_Config->getModelInstance('core/logger', Array)
#6 /var/www/makehandbuy-store/app/code/local/Bitbull/Satispay/Model/Logger.php(36): Mage::getModel('core/logger')
#7 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/Config.php(1357): Bitbull_Satispay_Model_Logger->__construct(true)
#8 /var/www/makehandbuy-store/app/Mage.php(473): Mage_Core_Model_Config->getModelInstance('satispay/logger', true)
#9 /var/www/makehandbuy-store/app/code/community/Bitbull/Satispay/Helper/Data.php(23): Mage::getModel('satispay/logger', true)
#10 /var/www/makehandbuy-store/app/Mage.php(557): Bitbull_Satispay_Helper_Data->__construct()
#11 /var/www/makehandbuy-store/app/code/community/Bitbull/Satispay/Model/Payment.php(85): Mage::helper('satispay')
#12 /var/www/makehandbuy-store/app/code/local/Idev/OneStepCheckout/Model/Observers/PresetDefaults.php(758): Bitbull_Satispay_Model_Payment->canUseForCurrency('EUR')
#13 /var/www/makehandbuy-store/app/code/local/Idev/OneStepCheckout/Model/Observers/PresetDefaults.php(729): Idev_OneStepCheckout_Model_Observers_PresetDefaults->_canUseMethod(Object(Bitbull_Satispay_Model_Payment), Object(Idev_OneStepCheckout_Model_Sales_Quote))
#14 /var/www/makehandbuy-store/app/code/local/Idev/OneStepCheckout/Model/Observers/PresetDefaults.php(679): Idev_OneStepCheckout_Model_Observers_PresetDefaults->getPaymentMethods(Object(Idev_OneStepCheckout_Model_Sales_Quote))
#15 /var/www/makehandbuy-store/app/code/local/Idev/OneStepCheckout/Model/Observers/PresetDefaults.php(75): Idev_OneStepCheckout_Model_Observers_PresetDefaults->setPaymentDefaults(Object(Varien_Event_Observer))
#16 /var/www/makehandbuy-store/app/code/local/Idev/OneStepCheckout/Model/Observers/PresetDefaults.php(59): Idev_OneStepCheckout_Model_Observers_PresetDefaults->callDefaults(Object(Varien_Event_Observer))
#17 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/App.php(1339): Idev_OneStepCheckout_Model_Observers_PresetDefaults->setDefaults(Object(Varien_Event_Observer))
#18 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/App.php(1312): Mage_Core_Model_App->_callObserverMethod(Object(Idev_OneStepCheckout_Model_Observers_PresetDefaults), 'setDefaults', Object(Varien_Event_Observer))
#19 /var/www/makehandbuy-store/app/Mage.php(458): Mage_Core_Model_App->dispatchEvent('sales_quote_col...', Array)
#20 /var/www/makehandbuy-store/app/code/core/Mage/Sales/Model/Quote.php(1245): Mage::dispatchEvent('sales_quote_col...', Array)
#21 /var/www/makehandbuy-store/app/code/local/Idev/OneStepCheckout/Model/Sales/Quote.php(44): Mage_Sales_Model_Quote->collectTotals()
#22 /var/www/makehandbuy-store/app/code/core/Mage/Checkout/Model/Session.php(225): Idev_OneStepCheckout_Model_Sales_Quote->collectTotals()
#23 /var/www/makehandbuy-store/app/code/core/Mage/Checkout/Model/Observer.php(44): Mage_Checkout_Model_Session->loadCustomerQuote()
#24 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/App.php(1339): Mage_Checkout_Model_Observer->loadCustomerQuote(Object(Varien_Event_Observer))
#25 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/App.php(1318): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Checkout_Model_Observer), 'loadCustomerQuo...', Object(Varien_Event_Observer))
#26 /var/www/makehandbuy-store/app/Mage.php(458): Mage_Core_Model_App->dispatchEvent('customer_login', Array)
#27 /var/www/makehandbuy-store/app/code/core/Mage/Customer/Model/Session.php(226): Mage::dispatchEvent('customer_login', Array)
#28 /var/www/makehandbuy-store/app/code/core/Mage/Customer/Model/Session.php(215): Mage_Customer_Model_Session->setCustomerAsLoggedIn(Object(Mage_Customer_Model_Customer))
#29 /var/www/makehandbuy-store/app/code/community/Youama/Ajaxlogin/Model/Ajaxlogin.php(49): Mage_Customer_Model_Session->login('andrea.zambon87...', 'p4ssw0rd')
#30 /var/www/makehandbuy-store/app/code/community/Youama/Ajaxlogin/Model/Ajaxlogin.php(40): Youama_Ajaxlogin_Model_Ajaxlogin->loginUser()
#31 /var/www/makehandbuy-store/lib/Varien/Object.php(112): Youama_Ajaxlogin_Model_Ajaxlogin->_construct()
#32 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/Config.php(1357): Varien_Object->__construct(Array)
#33 /var/www/makehandbuy-store/app/Mage.php(473): Mage_Core_Model_Config->getModelInstance('youama_ajaxlogi...', Array)
#34 /var/www/makehandbuy-store/app/Mage.php(487): Mage::getModel('youama_ajaxlogi...', Array)
#35 /var/www/makehandbuy-store/app/code/community/Youama/Ajaxlogin/controllers/AjaxController.php(36): Mage::getSingleton('youama_ajaxlogi...')
#36 /var/www/makehandbuy-store/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Youama_Ajaxlogin_AjaxController->indexAction()
#37 /var/www/makehandbuy-store/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#38 /var/www/makehandbuy-store/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#39 /var/www/makehandbuy-store/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#40 /var/www/makehandbuy-store/app/Mage.php(693): Mage_Core_Model_App->run(Array)
#41 /var/www/makehandbuy-store/index.php(94): Mage::run('', 'store')
#42 {main}

**Comment by renatocason** [comment]
Hi @azambon,

I have _display_errors_ and _display_startup_errors_ set to _On_ in my development environment, plus _error_reporting_ set to _E_ALL_, but still I get neither the warning nor the exception.
Anyway, I removed the _core/logger_ inclusion, as it was wrapping _Mage::log_ itself.
Can you give that a try, and see if the new revision 0.2.3 fixes this issue and #5?

Thanks,
Renato

**Comment by azambon** [comment]
Just checked, not it works just fine :)
Perhaps the problem is because I use PHP 7.0.25? But still, removing the getModel call entirely removes the error.

To be pedantic, there would be another tiny thing to fix: the version number inside etc/config.xml does not match the git tag name. This seems to upset packages.firegento.com, which fails to see the latest module versions: http://packages.firegento.com/#!/satispay
I bypassed this by adding an explicit reference to this repo in my composer.json file, but it would be preferable not to be forced to do so.
If you prefer I can open a separate issue for this.

**Comment by renatocason** [comment]
Hi @azambon,

Can you make another test now?
I updated the version with the new release, after including your PRs.

Thanks,
Renato

**Comment by azambon** [comment]
Hi @renatocason,

Thank you for the PR merges and for the version bump. And also for the addition to the contributors file :)

I'll update the module and check again tomorrow.
I mentioned the issue with packages.firegento.com as I seemed to remember a similar problem with one of our modules, but most likely I remember something wrong and the version number mismatch has no link to the missing versions on firegento, as you say.

As for the last line in your message, I'm already installing this module from this Github repo:

"repositories": [
...
    {
        "type": "vcs", 
        "url": "git@github.com:bitbull-team/magento-module-satispay.git" 
    }

Perhaps you meant the other way around? That is use Packagist instead of Github? That actually makes perfect sense, I should have thought of that sooner...

**Comment by renatocason** [comment]
Hi @azambon,

That is weird, if you are using the repository it should include the module via Git and not via Firegento. I also fixed the composer module name to be lower case and added it to Packagist (version 0.2.5) - let's see if this time it works!

Thanks for your patience!

Renato

**Comment by azambon** [comment]
Hi @renatocason,

I think there was a misunderstanding here: At first I tried to install your module using firegento. That worked, but I didn't ger the latest version of the module. So I switched to the github repo and all was solved, I got the latest version.
Packagist didn't even cross my mind for some reason, stupid me...

So theoretically it should be enough to use Packagist to get the latest version of the module, as I can see that all of the tags are there: https://packagist.org/packages/bitbull/satispay

As I said I'll try again later today.

Thanks for **your** patience :)

**Comment by azambon** [comment]
Hi @renatocason,

just completed the test, and it all seems to work fine. I removed the github reference from my composer.json so that packagist is used in stead and composer found the latest module version right away. No errors with the module or anything else.

So I'd say we can close these two issues :)

**Comment by renatocason** [comment]
Hi @azambon,

Amazing, thanks for the feedback!

Regards,
Renato
